name = "siren-web"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-23"
minify = true
workers_dev = true
routes = [

  { pattern = "vvip.rzw.biz.id", custom_domain = true },
  { pattern = "ava.game.naver.com.wc.rzw.biz.id", custom_domain = true },
  { pattern = "demo.appsflyer.com.wc.rzw.biz.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.wc.rzw.biz.id", custom_domain = true },
  { pattern = "graph.instagram.com.wc.rzw.biz.id", custom_domain = true },
  { pattern = "blog.webex.com.wc.rzw.biz.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.wc.rzw.biz.id", custom_domain = true },
  { pattern = "bimbel.ruangguru.com.wc.rzw.biz.id", custom_domain = true },
  { pattern = "support.zoom.us.wc.rzw.biz.id", custom_domain = true },
  { pattern = "cache.netflix.com.wc.rzw.biz.id", custom_domain = true },
  { pattern = "investor.fb.com.wc.rzw.biz.id", custom_domain = true },
  { pattern = "nontontv.vidio.com.wc.rzw.biz.id", custom_domain = true },
  { pattern = "blog.clova.line.me.wc.rzw.biz.id", custom_domain = true },
]

[[kv_namespaces]]
binding = "SIREN"
id = "f35490ce191e4d7289968b2cf5a76427"

[build]
command = "cargo install -q worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install -q worker-build && worker-build --dev" }

[vars]
UUID = "aacac2d2-cac8-442a-9f2c-4e4f807065f5"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/thissrerre/SirenWeb/refs/heads/main/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/thissrerre/SirenWeb/refs/heads/main/web/sub.html"
LINK_PAGE_URL = "https://raw.githubusercontent.com/thissrerre/SirenWeb/refs/heads/master/web/link.html"
